export type SoundEvent =
  | 'OBJECT_PICKED_UP'
  | 'OBJECT_PLACED'
  | 'OBJECT_WOBBLED'
  | 'OBJECT_FELL'
  | 'ACTOR_SPOTTED_OBJECT'
  | 'ACTOR_JUMPED'
  | 'GOAL_STABILITY_STARTED'
  | 'GOAL_COMPLETED'
  | 'GOAL_FAILED';
